In [1]:
import os
import sys
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
file_path1 = r'data\email_dump.csv'

In [3]:
data = pd.read_csv(file_path1)
data.head()

,id,from_email,to_email,cc_email,subject,date_ist,time_ist,projectid,cleaned_body,label,score,run_time
0,c6904740-a079-4dd7-89b3-f4a3998a1f7c,jayla.horton@msssolutions.com,aghosh1@pinnacleinfotech.com,"steven.cantrill@msssolutions.com, chris.little...",Atrium BT - Pipe Guide,2024-10-07,23:54:04,53397,"For BT, please use the same pipe guides as CFE.",POSITIVE,0.3182,1728328159
1,223afaea-5c55-4dda-bff8-c07085e8d5c4,k.hemphill@fitzplumb.com,"t.heard@fitzplumb.com, jaganathd@pinnacleinfot...","j.casey@fitzplumb.com, asaha@pinnacleinfotech.com",RE: Fitz: Switch NAP 4 TI - Shop Drawings : Ar...,2024-10-07,21:08:13,79441,NaN,NEUTRAL,0.0000,1728328159
2,a6900667-6119-41ca-849a-3e136c84ec57,adamf@amfmep.co.uk,"krai@pinnacleinfotech.com, arpanc@pinnacleinfo...","graceh@amfmep.co.uk, stevep@amfmep.co.uk",IES Alder Castle,2024-10-04,13:38:42,80057,"All, Please see below link to Architect's RCP ...",POSITIVE,0.5327,1728036608
3,90873f0a-93ec-4e87-9666-4eb93fd1d112,omar.zaarour@nesmapartners.com,"swarupg@pinnacleinfotech.com, basel.salaas@nes...","sujith.subramaniam@nesmapartners.com, schaba@p...",RE: Plot 37,2024-10-05,14:09:30,63901,"For the sake of accuracy, these revisions were...",POSITIVE,0.6249,1728122966
4,a1a9db98-4c58-4346-8efd-287e8ec84df5,mdaniel@joneseng.com,nkoley@pinnacleinfotech.com,pmoriarty@joneseng.com,RE: HH5- ROOF plant room markup,2024-10-07,17:56:53,77583,Apologize it should be mm Regards\nMathew Dani...,POSITIVE,0.1027,1728313826

In [4]:
data.to_parquet('data/email_parquet.parquet')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   projectid                     29 non-null     int64
 1   breakupid                     29 non-null     int64
 2   pdh_name                      29 non-null     object
 3   contracthours                 29 non-null     object
 4   contractvalue                 21 non-null     object
 5   requestdate                   29 non-null     datetime64[ns]
 6   requested_by                  29 non-null     object
 7   approved_by                   29 non-null     object
 8   approveddate                  29 non-null     datetime64[ns]
 9   approvalstatus                29 non-null     bool
 10  correctedhour                 0 non-null      object
 11  correctedvalue                0 non-null      object
 12  files                         23 non-null     object
 13  ponumber                      2 non-null      object
 14  podate                        2 non-null      datetime64[ns]
 15  CO_contracthours_brkp_apprvd  29 non-null     object
 16  CO_contractvalue_brkp_apprvd  22 non-null     object
 17  CO_contracthours_brkp_pend    27 non-null     object
 18  CO_contractvalue_brkp_pend    17 non-null     object
 19  CO_contracthours_prj_apprvd   29 non-null     object
 20  CO_contractvalue_prj_apprvd   22 non-null     object
 21  CO_contracthours_prj_pend     27 non-null     object
 22  CO_contractvalue_prj_pend     17 non-null     object
 23  CO_Raised                     29 non-null     int64
 24  CO_Approved                   29 non-null     int64
dtypes: bool(1), datetime64[ns](3), int64(4), object(17)
memory usage: 5.6+ KB

In [16]:
file_path2 = r'data\RCA_259_N.parquet'
data1 = pd.read_parquet(file_path2)
data1.head()

,id,org_id,user_email,plugin_id,project_id,package_name,package_version,plugin_version,num_elements_processed,time_taken_ms,desktop_usage_timestamp,timestamp,filename,software_name,mac_address,ip_address,device_type,pdh_id,is_error,error_message
0,3df73b21-a313-415f-9d7e-6453da41025b,259,mayank.vyas@jpr.pinnacleinfotech.com,c9f233c6-8522-49a3-a305-68f572f22742,77047,Pi Mechanical,3.5.0,1.0.0,1,386.0,1707268921,1707268947,C:\Users\pis02770\AppData\Local\Autodesk\Revit...,Autodesk Revit 2021,A08CFDE7CED7,14.97.108.222,RestSharp/105.2.3.0,1748,None,None
1,f21722e7-e1cd-48c7-923e-03359ade113d,259,mayank.vyas@jpr.pinnacleinfotech.com,c9f233c6-8522-49a3-a305-68f572f22742,77047,Pi Mechanical,3.5.0,1.0.0,1,6029.0,1707268922,1707268947,C:\Users\pis02770\AppData\Local\Autodesk\Revit...,Autodesk Revit 2021,A08CFDE7CED7,14.97.108.222,RestSharp/105.2.3.0,1748,None,None

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2 non-null      object
 1   org_id                   2 non-null      object
 2   user_email               2 non-null      object
 3   plugin_id                2 non-null      object
 4   project_id               2 non-null      object
 5   package_name             2 non-null      object
 6   package_version          2 non-null      object
 7   plugin_version           2 non-null      object
 8   num_elements_processed   2 non-null      int32
 9   time_taken_ms            2 non-null      float32
 10  desktop_usage_timestamp  2 non-null      object
 11  timestamp                2 non-null      object
 12  filename                 2 non-null      object
 13  software_name            2 non-null      object
 14  mac_address              2 non-null      object
 15  ip_address               2 non-null      object
 16  device_type              2 non-null      object
 17  pdh_id                   2 non-null      object
 18  is_error                 0 non-null      object
 19  error_message            0 non-null      object
dtypes: float32(1), int32(1), object(18)
memory usage: 432.0+ bytes

In [13]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2 non-null      object
 1   org_id                   2 non-null      object
 2   user_email               2 non-null      object
 3   plugin_id                2 non-null      object
 4   project_id               2 non-null      object
 5   package_name             2 non-null      object
 6   package_version          2 non-null      object
 7   plugin_version           2 non-null      object
 8   num_elements_processed   2 non-null      int32
 9   time_taken_ms            2 non-null      float32
 10  desktop_usage_timestamp  2 non-null      object
 11  timestamp                2 non-null      object
 12  filename                 2 non-null      object
 13  software_name            2 non-null      object
 14  mac_address              2 non-null      object
 15  ip_address               2 non-null      object
 16  device_type              2 non-null      object
 17  pdh_id                   2 non-null      object
 18  is_error                 0 non-null      object
 19  error_message            0 non-null      object
dtypes: float32(1), int32(1), object(18)
memory usage: 432.0+ bytes

In [19]:
file_path2 = r'data\RCA_287.parquet'
data2 = pd.read_parquet(file_path2)
data2.head()

,id,org_id,user_email,plugin_id,project_id,package_name,package_version,plugin_version,num_elements_processed,time_taken_ms,desktop_usage_timestamp,timestamp,filename,software_name,mac_address,ip_address,device_type,pdh_id,is_error,error_message
0,ffd16178-0167-4202-af77-59237e6c3977,287,gheyse@swansonrink.com,57b940c2-5ced-476c-b7a4-3528660f42a1,0,Pi SWR,1.0.0,1.0.0,1,377.0,1707330961,1707330962,Autodesk Docs://LAS T1 Node 4/3080.R23_LAS T1 ...,Autodesk Revit 2023,00090FAA0001,205.168.107.219,RestSharp/106.12.0.0,0,None,None

In [21]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       1 non-null      object
 1   org_id                   1 non-null      object
 2   user_email               1 non-null      object
 3   plugin_id                1 non-null      object
 4   project_id               1 non-null      object
 5   package_name             1 non-null      object
 6   package_version          1 non-null      object
 7   plugin_version           1 non-null      object
 8   num_elements_processed   1 non-null      int32
 9   time_taken_ms            1 non-null      float32
 10  desktop_usage_timestamp  1 non-null      object
 11  timestamp                1 non-null      object
 12  filename                 1 non-null      object
 13  software_name            1 non-null      object
 14  mac_address              1 non-null      object
 15  ip_address               1 non-null      object
 16  device_type              1 non-null      object
 17  pdh_id                   1 non-null      object
 18  is_error                 0 non-null      object
 19  error_message            0 non-null      object
dtypes: float32(1), int32(1), object(18)
memory usage: 280.0+ bytes